services:
  app:
    build: .
    container_name: agua_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=agua_potable
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - mysql
    networks:
      - agua
    

  mysql:
    image: mysql:8.0
    container_name: agua_mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: agua_potable
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - agua

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: agua_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    depends_on:
      - mysql
    networks:
      - agua

volumes:
  mysql_data:

networks:
  agua:
